#1- ping scan for get hosts up =>IPsPing.txt 
#2- port scan for get the ports on IpsPing=>IPsPort.txt
#3- services scan for get the services runing on IPsPort=>IPsServices   

name: 00-autoNetworkScan

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#------------------------update  os + nmap install and update
    - name: update  os + nmap install and update
      run: sudo apt update  && sudo apt install nmap && sudo nmap --script-updatedb   && echo "------------------update  os + nmap install and update done"  

#========================================================================nmap
#-----------------------nmap ping + open port  range
    #- name: nmap ping
      #run: |
       #sudo nmap -v -n -sS --open --min-rate 100000 -p 445 -script smb-vuln-ms08-067.nse -script-args=unsafe=1 12.0-255.0-255.0-255 -oN nmapPing.txt
       #echo "---------------ls" && ls
       #echo "---------------cat nmapPing.txt" && cat nmapPing.txt  
       

#-----------------------nmap ping + open port       
    - name: nmap ping
      run: |
       sudo nmap -v -n -sS --min-rate 100000 -p- 69.5.17.174 -oN nmapPing.txt -d 
       echo "---------------ls" && ls
       echo "---------------cat nmapPing.txt" && cat nmapPing.txt       
     
      
       
       
#masscan -iL ip_list.txt -p 80       
#-A: Enable OS detection, version detection, script scanning, and traceroute =>details about the version of running services and also points out any vulnerabilities
#-sS =>nmap -sS 0.0.0.0=> quickly scans multiple ports within the shortest time possible     
#-sn if you just want to know which remote hosts are alive       
#-n :disable reverse DNS resolution lazem tkoun            
#-v :enables verbose mode=> show how mutsh data send
#-Pn (No ping):skips the host discovery =>even if the host dont responce to ping ,scan it
#-sP:Skip port scan=>ping scan
#-sn:(No port scan)
#-sS: TCP SYN scan=>sceep the therd hand shack
#4444444444444 nmap safe scan 
          #=>nmap -p 445 -script smb-check-vulns -script-args=unsafe=1 <IP Address>
# nmap -p 22 -oG - 192.168.1.24 | grep 22/open =>Host: 192.168.1.20 (arcadia.house)  Ports: 22/open/tcp//ssh///
# nmap -v -n -p- 0.0.0.0 =>fi 2.2 minut =>open ports+version  
#sudo nmap -Pn -n -v -sS --open -T5 --max-rtt-timeout 1s --min-parallelism 100 -p8983  65-75.0-255.0-255.0-255 -oN nmap000_010.txt -d 
#nmap -sP 208.109.192.1-255 =>png scan

