name: 01-nikto

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latestF
    steps:
#---------------------------------------------------update 
    - name: update
      run: sudo apt update
#---------------------------------------------------nikto
    - name: nikto install 
      run:  sudo apt install nikto
    - name: nikto scan
      run: |
       nikto -h st.iqraa.opu.dz
