name: 01-n0i0k0t0o0

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#------------------------update  os
    - name: update  os + nmap install and update
      run: sudo apt update
#---------------------------------------------------nikto
    - name: nikto install 
      run:  sudo apt install nikto
    - name: nikto scan
      run: |
       nikto -h st.iqraa.opu.dz 
