name: autoMasscanNmapLftp

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #------------------------update  
    - name: update
      run: sudo apt update
      #=======================================================================masscan 
      #------------------------masscan install
    - name: install masscan
      run: sudo apt install masscan
      #------------------------masscan scan +build file masscan0_1.txt of ips on port 8983
      #change on => "name: masscan0_1" + "> masscan0_1.txt"+ "echo masscan0_1.txt" + "cat masscan0_1.txt"+++++++++IP
    - name: masscan0_1
      run: | 
       echo "------------------start scan"      
       sudo masscan -p8983 4.4.119.0-4.4.119.255 --rate=1000000 |grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' >masscan0_1.txt       
       echo "---------------ls" && ls && echo "---------------cat masscan0_1.txt" && cat masscan0_1.txt      
      #========================================================================nmap
      #-------------------------nmap  instal and update db
    - name: n0m0a0p install and update db
      run: sudo apt install nmap && sudo nmap --script-updatedb  
      #-------------------------nmap scan +build file nmap0_1.txt on port 8983
    - name: nmap0_1
      run: |
       sudo nmap -Pn -sV -p8983 -iL masscan0_1.txt -oN nmap0_1.txt -d
       echo "---------------ls" && ls && echo "---------------cat nmap0_1.txt" && cat nmap0_1.txt 
     
       
       
       
       
       
       
       #==================================================================LFTP
       #----------------------------------------install LFTP
    - name: install lftp
      run: sudo apt install lftp
    - name: lftp
      run: |
       #echo "----------------------------------test lftp "
       #lftp ounoua:'aaazzzeee@1N'@files.000webhost.com  -e "ls"
       #echo "----------------------------------upload file "
       #lftp ounoua:'aaazzzeee@1N'@files.000webhost.com  -e "put mass.txt;ls;exit;"
       echo "----------------------------------don "
