# masscan kell ma tkabar fi el majal kel ma yzid la vitess
name: autoMasscanNmapLftp

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#------------------------update  os + Lftp install
    - name: update + Lftp install
      run: sudo apt update  && sudo apt install lftp && echo "------------------update + lftp install done"  
#=======================================================================masscan 
#------------------------masscan install
    - name: install masscan
      run: sudo apt install masscan
#------------------------masscan scan +build file masscan000_010.txt of ips on port 8983
    - name: masscan000_010.txt
      run: | 
       echo "------------------start scan"      
       #sudo masscan -p8983 0.0.0.0-10.0.0.0 --rate=1000000 |grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' >masscan000_010.txt  
       sudo masscan -p389 100.128.0.0-100.255.255.255 --rate=100000 |grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' >masscan000_010.txt      
       echo "---------------ls" && ls && echo "---------------cat masscan000_010.txt" && cat masscan000_010.txt    
       echo "---------------start upload masscan000_010.txt with LFTP "
       #lftp ounoua:'aaazzzeee@1N'@files.000webhost.com  -e "put masscan000_010.txt;exit;"
       sudo masscan -iL masscan000_010.txt -p80 --rate=100000 |grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' >masscan000_0102.txt 
       echo "---------------ls" && ls && echo "---------------cat masscan000_0102.txt" && cat masscan000_0102.txt 
       F
       
#========================================================================nmap
#-------------------------nmap  instal and update db
    - name: n0m0a0p install and update db
      run: sudo apt install nmap && sudo nmap --script-updatedb  
#-------------------------nmap scan +build file nmap000_010.txt on port 8983
    - name: nmap000_010.txt
      run: |
       sudo nmap -Pn -sV -p8983 -iL masscan000_010.txt -oN nmap000_010.txt -d             
       echo "---------------ls" && ls && echo "---------------cat nmap000_010.txt" && cat nmap000_010.txt 
       echo "---------------start upload nmap000_010.txt with LFTP "
       lftp ounoua:'aaazzzeee@1N'@files.000webhost.com  -e "put  nmap000_010.txt;exit;"
            





       #==================================================================LFTP
       #----------------------------------------install LFTP
    #- name: install lftp
      #run: sudo apt install lftp
    #- name: lftp
      #run: |
       #echo "----------------------------------test lftp "
       #lftp ounoua:'aaazzzeee@1N'@files.000webhost.com  -e "ls"
       #echo "----------------------------------upload file "
       #lftp ounoua:'aaazzzeee@1N'@files.000webhost.com  -e "put mass.txt;ls;exit;"
       #echo "----------------------------------don "
       
       
       
#masscan -iL ip_list.txt -p 80       
#-A nmap -A 192.168.2.107 =>details about the version of running services and also points out any vulnerabilities
#-sS =>nmap -sS 192.168.2.107=> quickly scans multiple ports within the shortest time possible     
#-sn if you just want to know which remote hosts are alive       
#-n parameter to disable reverse DNS resolution lazem tkoun       
# nmap -v -n -p- sec.titan.net =>fi 2.2 minut =>open ports+version       
#-v virbose moade: show how mutsh data send
# nmap -p 22 -oG - 192.168.1.24 | grep 22/open =>Host: 192.168.1.20 (arcadia.house)  Ports: 22/open/tcp//ssh///
