# masscan kell ma tkabar fi el majal kel ma yzid la vitess
name: autoMasscanNmapLftp

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #------------------------update  
    - name: update
      run: sudo apt update
      #=======================================================================masscan 
      #------------------------masscan install
    - name: install masscan
      run: sudo apt install masscan
      #------------------------masscan scan +build file masscan0_1.txt of ips on port 8983
      #change on => "name: masscan0_1" + "> masscan0_1.txt"+ "echo masscan0_1.txt" + "cat masscan0_1.txt"+++++++++IP
    - name: masscan0_1
      run: | 
       echo "------------------start scan"      
       sudo masscan -p8983 110.0.0.0-110.1.0.0 --rate=1000000 |grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' >masscan0_1.txt       
       echo "---------------ls" && ls && echo "---------------cat masscan0_1.txt" && cat masscan0_1.txt      
      #========================================================================nmap
      #-------------------------nmap  instal and update db
    - name: n0m0a0p install and update db
      run: sudo apt install nmap && sudo nmap --script-updatedb  
      #-------------------------nmap scan +build file nmap0_1.txt on port 8983
    - name: nmap0_1
      run: |
       #sudo nmap -Pn -sV -p8983 -iL masscan0_1.txt -oN nmap0_1.txt -d
       #echo "---------------ls" && ls && echo "---------------cat nmap0_1.txt" && cat nmap0_1.txt 
       sudo nmap -v -n -oG -p8983 -iL masscan0_1.txt -oN nmap0_1.txt
        
       
       
       
       

       #==================================================================LFTP
       #----------------------------------------install LFTP
    - name: install lftp
      run: sudo apt install lftp
    - name: lftp
      run: |
       #echo "----------------------------------test lftp "
       #lftp ounoua:'aaazzzeee@1N'@files.000webhost.com  -e "ls"
       #echo "----------------------------------upload file "
       #lftp ounoua:'aaazzzeee@1N'@files.000webhost.com  -e "put mass.txt;ls;exit;"
       echo "----------------------------------don "
       
       
       
       
       
       
       
       
# nmap -v -n -p- sec.titan.net =>fi 2.2 minut =>open ports+version       
#-v virbose moade: show how mutsh data send
# nmap -p 22 -oG - 192.168.1.24 | grep 22/open =>Host: 192.168.1.20 (arcadia.house)  Ports: 22/open/tcp//ssh///
