#mechkal mana3raf
name: gobusterDirb

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#---------------------------------------------------update 
    - name: update
      run: sudo apt update
#---------------------------------------------------gobusterDirb
    - name: gobusterDirb install 
      run:  sudo apt install gobuster && sudo apt install dirb
    - name: gobuster scan
      run: |
       echo "--------------cd and ls" && cd .. && cd .. && cd .. && cd .. && cd .. && ls
       sudo gobuster
       sudo gobuster dns -d google.com
       #sudo gobuster dir -e -u st.iqraa.opu.dz -w /usr/share/wordlists/dirb/common.txt
          
          
