name: gobusterDirb

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#---------------------------------------------------update 
    - name: update
      run: sudo apt update
#---------------------------------------------------gobusterDirb
    - name: gobusterDirb install 
      run:  sudo apt install gobuster && sudo apt install dirb
    - name: gobuster scan
      run: |
       ls /usr/share/wordlists/dirb/
       ls /home/
       sudo gobuster dir -e -u google.com -w /usr/share/wordlists/dirb/common.txt
       
       
       
