name: n0i0k0t0o

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latestF
    steps:
#---------------------------------------------------update 
    - name: update
      run: sudo apt update
#---------------------------------------------------n0i0k0t0o
    - name: n0i0k0t0o install 
      run:  sudo apt install nikto
    - name: n0i0k0t0o scan
      run: |
       nikto -h a.com
